name = "dfd-supply"
compatibility_date = "2026-03-23"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "test"
database_id = "96a4bad1-60b6-4f74-b629-8ccb13844a96"
migrations_dir = "migrations"
