name = "test"
main = "src/index.js"
compatibility_date = "2026-03-23"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "test"
database_id = "96a4bad1-60b6-4f74-b629-8ccb13844a96"
migrations_dir = "migrations"
